version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint:
      - ./docker-entrypoint.sh
    environment:
        FILE: data/data.csv
        FORMAT: json
        ORDER: asc
        FIELD: Name
    volumes:
      - ".:/go/src/github.com/fabriciojsil/convert-csv-data"
